### ISSUE TITLE
Please review this usage of kernel headers.

### ISSUE THREAD

**Issue by infixremix** [AospExtended/platform_build#11]
https://github.com/AospExtended/platform_build/blob/9.x/core/binary.mk#L36
Please review the usage of the new implementation of new kernel headers. It causes issues for alot of devices. However commenting it out fixes the issue and has no deptermentual affect on the build.

**Comment by theimpulson** [comment]
If this issue is still relevant, please push patch on gerrit. Closing old issues in absence of any activity.
